### PR TITLE
Removed rubysl-resolv dependency and explicit require

### PR DESCRIPTION
**Pull request by kgorin**
@jimm I am trying to improve start-up time for our dev environment and at some point I got a lot of `already initialized constant` warnings:

```
/Users/kgorin/.rvm/gems/ruby-2.3.1@Candi/gems/rubysl-resolv-2.1.2/lib/rubysl/resolv/resolv.rb:172: warning: already initialized constant Resolv::Hosts::DefaultFileName
/Users/kgorin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:175: warning: previous definition of DefaultFileName was here
/Users/kgorin/.rvm/gems/ruby-2.3.1@Candi/gems/rubysl-resolv-2.1.2/lib/rubysl/resolv/resolv.rb:285: warning: already initialized constant Resolv::DNS::Port
/Users/kgorin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:288: warning: previous definition of Port was here
/Users/kgorin/.rvm/gems/ruby-2.3.1@Candi/gems/rubysl-resolv-2.1.2/lib/rubysl/resolv/resolv.rb:290: warning: already initialized constant Resolv::DNS::UDPSize
/Users/kgorin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:293: warning: previous definition of UDPSize was here
/Users/kgorin/.rvm/gems/ruby-2.3.1@Candi/gems/rubysl-resolv-2.1.2/lib/rubysl/resolv/resolv.rb:624: warning: already initialized constant Resolv::DNS::RequestID
/Users/kgorin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:627: warning: previous definition of RequestID was here
/Users/kgorin/.rvm/gems/ruby-2.3.1@Candi/gems/rubysl-resolv-2.1.2/lib/rubysl/resolv/resolv.rb:625: warning: already initialized constant Resolv::DNS::RequestIDMutex
/Users/kgorin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:628: warning: previous definition of RequestIDMutex was here
/Users/kgorin/.rvm/gems/ruby-2.3.1@Candi/gems/rubysl-resolv-2.1.2/lib/rubysl/resolv/resolv.rb:1077: warning: already initialized constant Resolv::DNS::Config::InitialTimeout
/Users/kgorin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:1084: warning: previous definition of InitialTimeout was here
```

I noticed that we have `rubysl-resolv` in gem dependencies and explicitly require it in `shopify_api.rb`, but looks like it is available in ruby 2.3 by default. Can we safely remove this dependency?

### CODE REVIEW

**Comment by Tonkpils** [comment]
👍 looks like this is good.

**Comment by jimm** [comment]
I'm loathe to change this because if we ever want to offer this as a PR to the main active_fulfillment gem we'd have a difference in the gemspec and in shopify_api.rb. Might there be a way to monkeypatch in our app to avoid the reload?

**Comment by davidguthu** [comment]
Seems like a good call Jim.

David Guthu

**Comment by davidguthu** [comment]
Kirill, 

Have you identified where we spend the most time in app loading? 

David Guthu

**Comment by kgorin** [comment]
@jimm good call, looking into that
@davidguthu apparently expanding relative paths to absolute takes quite some time in general and we have lots of gems. So this work addresses just that. And it's a relatively easy fix.

**Comment by kgorin** [comment]
@jimm Shopify/active_fulfillment@master does not have `rubysl-resolv` as dependency in gemspec, so this PR is actually closer to the base branch

**Comment by jimm** [comment]
👍 @kgorin you are correct, I was looking at the wrong thing.

**Comment by jimm** [comment]
@kgorin don't forget to upgrade the Candi version of AF to a5ca3f013d54d98218e3afbb7bacf95933d440b3

**Pull request merged**
